#define MOTOR1_PWM 9
#define MOTOR1_DIR 8
#define MOTOR1_ENCODER_A 7
#define MOTOR1_ENCODER_B 6

#define MOTOR2_PWM 10
#define MOTOR2_DIR 11
#define MOTOR2_ENCODER_A 15
#define MOTOR2_ENCODER_B 14

#define MOTOR3_PWM 3
#define MOTOR3_DIR 2
#define MOTOR3_ENCODER_A 5
#define MOTOR3_ENCODER_B 4
